---
classification: "aerovane"
ch_interval_sec: 0.2
meas_cycle_sec: 0.4
num_buffer: 10
num_rpt: 0
meas_chs:
  - 0
  - 1
ch_role:
  0: "wind_spd"
  1: "wind_dir"
conv_factor:
  0: 60
  1: 360
volt_range:
  0: 1
  1: 1