version: "2"

services:
  influxdb:
    image: influxdb
    volumes:
      - /tmp/influxdb:/var/lib/influxdb
    ports:
      - "8083:8083"
      - "8086:8086"

  grafana:
    image: grafana/grafana
    volumes:
      - /tmp/grafana:/var/lib/grafana
    ports:
      - "3000:3000"
    environment:
      - INFLUXDB_PROTO=http
      - INFLUXDB_HOST=influxdb
      - INFLUXDB_PORT=8086
